// This file is auto-generated by: npx supabase gen types typescript --project-id YOUR_ID > types/database.ts
// Run this command after finalizing your DB schema to get fully-typed queries.
// Below is a placeholder that matches the planned schema.

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

export type Database = {
  public: {
    Tables: {
      profiles: {
        Row: {
          id: string;
          full_name: string | null;
          phone: string | null;
          phone_verified: boolean;
          avatar_url: string | null;
          stripe_customer_id: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id: string;
          full_name?: string | null;
          phone?: string | null;
          phone_verified?: boolean;
          avatar_url?: string | null;
          stripe_customer_id?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          full_name?: string | null;
          phone?: string | null;
          phone_verified?: boolean;
          avatar_url?: string | null;
          stripe_customer_id?: string | null;
          updated_at?: string;
        };
        Relationships: [];
      };
      routes: {
        Row: {
          id: string;
          driver_id: string;
          origin_city: string;
          origin_country: string;
          destination_city: string;
          destination_country: string;
          departure_date: string;
          estimated_arrival_date: string | null;
          available_weight_kg: number;
          price_per_kg_eur: number;
          status: string;
          notes: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          driver_id: string;
          origin_city: string;
          origin_country: string;
          destination_city: string;
          destination_country: string;
          departure_date: string;
          estimated_arrival_date?: string | null;
          available_weight_kg: number;
          price_per_kg_eur: number;
          status?: string;
          notes?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          available_weight_kg?: number;
          price_per_kg_eur?: number;
          status?: string;
          notes?: string | null;
          estimated_arrival_date?: string | null;
          updated_at?: string;
        };
        Relationships: [];
      };
      route_stops: {
        Row: {
          id: string;
          route_id: string;
          city: string;
          country: string;
          stop_order: number;
          arrival_date: string | null;
          is_pickup_available: boolean;
          is_dropoff_available: boolean;
        };
        Insert: {
          id?: string;
          route_id: string;
          city: string;
          country: string;
          stop_order: number;
          arrival_date?: string | null;
          is_pickup_available?: boolean;
          is_dropoff_available?: boolean;
        };
        Update: {
          arrival_date?: string | null;
          is_pickup_available?: boolean;
          is_dropoff_available?: boolean;
        };
        Relationships: [];
      };
      bookings: {
        Row: {
          id: string;
          sender_id: string;
          route_id: string;
          package_weight_kg: number;
          package_category: string;
          package_photos: string[] | null;
          pickup_type: string;
          pickup_address: string | null;
          dropoff_type: string;
          dropoff_address: string | null;
          declared_value_eur: number | null;
          price_eur: number;
          stripe_payment_intent_id: string | null;
          payment_status: string;
          status: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          sender_id: string;
          route_id: string;
          package_weight_kg: number;
          package_category: string;
          package_photos?: string[] | null;
          pickup_type: string;
          pickup_address?: string | null;
          dropoff_type: string;
          dropoff_address?: string | null;
          declared_value_eur?: number | null;
          price_eur: number;
          stripe_payment_intent_id?: string | null;
          payment_status?: string;
          status?: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          package_photos?: string[] | null;
          pickup_address?: string | null;
          dropoff_address?: string | null;
          stripe_payment_intent_id?: string | null;
          payment_status?: string;
          status?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      shipping_requests: {
        Row: {
          id: string;
          sender_id: string;
          origin_city: string;
          origin_country: string;
          destination_city: string;
          destination_country: string;
          desired_date_from: string | null;
          desired_date_to: string | null;
          package_weight_kg: number;
          package_category: string;
          max_budget_eur: number | null;
          status: string;
          expires_at: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          sender_id: string;
          origin_city: string;
          origin_country: string;
          destination_city: string;
          destination_country: string;
          desired_date_from?: string | null;
          desired_date_to?: string | null;
          package_weight_kg: number;
          package_category: string;
          max_budget_eur?: number | null;
          status?: string;
          expires_at?: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          status?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      shipping_request_offers: {
        Row: {
          id: string;
          request_id: string;
          driver_id: string;
          proposed_price_eur: number;
          proposed_pickup_date: string | null;
          message: string | null;
          status: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          request_id: string;
          driver_id: string;
          proposed_price_eur: number;
          proposed_pickup_date?: string | null;
          message?: string | null;
          status?: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          status?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      ratings: {
        Row: {
          id: string;
          booking_id: string;
          sender_id: string;
          driver_id: string;
          score: number;
          comment: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          booking_id: string;
          sender_id: string;
          driver_id: string;
          score: number;
          comment?: string | null;
          created_at?: string;
        };
        Update: {
          comment?: string | null;
        };
        Relationships: [];
      };
      disputes: {
        Row: {
          id: string;
          booking_id: string;
          sender_id: string;
          reason: string;
          description: string;
          evidence_urls: string[] | null;
          status: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          booking_id: string;
          sender_id: string;
          reason: string;
          description: string;
          evidence_urls?: string[] | null;
          status?: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          status?: string;
          evidence_urls?: string[] | null;
          updated_at?: string;
        };
        Relationships: [];
      };
      saved_addresses: {
        Row: {
          id: string;
          user_id: string;
          label: string;
          street: string;
          city: string;
          country: string;
          postal_code: string | null;
          is_default: boolean;
          created_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          label: string;
          street: string;
          city: string;
          country: string;
          postal_code?: string | null;
          is_default?: boolean;
          created_at?: string;
        };
        Update: {
          label?: string;
          street?: string;
          city?: string;
          country?: string;
          postal_code?: string | null;
          is_default?: boolean;
        };
        Relationships: [];
      };
    };
    Views: Record<string, never>;
    Functions: Record<string, never>;
    Enums: Record<string, never>;
    CompositeTypes: Record<string, never>;
  };
};

export type Tables<T extends keyof Database['public']['Tables']> =
  Database['public']['Tables'][T]['Row'];
export type Insert<T extends keyof Database['public']['Tables']> =
  Database['public']['Tables'][T]['Insert'];
export type Update<T extends keyof Database['public']['Tables']> =
  Database['public']['Tables'][T]['Update'];
